import unicorn from 'eslint-plugin-unicorn';

export default {
  ...unicorn.configs.recommended.rules,
  'unicorn/filename-case': [
    'error',
    {
      cases: {
        camelCase: true,
        pascalCase: true,
      },
    },
  ],
  'unicorn/prefer-node-protocol': 'error',
  'unicorn/prevent-abbreviations': [
    'error',
    {
      allowList: {
        acc: true,
        api: true,
        apis: true,
        app: true,
        apps: true,
        arg: true,
        args: true,
        cfg: true,
        config: true,
        ctx: true,
        db: true,
        dto: true,
        env: true,
        err: true,
        getInitialProps: true,
        getServerSideProps: true,
        getStaticPaths: true,
        getStaticProps: true,
        id: true,
        ids: true,
        msg: true,
        obj: true,
        param: true,
        params: true,
        prop: true,
        Prop: true,
        props: true,
        Props: true,
        ref: true,
        refs: true,
        req: true,
        res: true,
        src: true,
        stat: true,
        stats: true,
        temp: true,
        tmp: true,
        url: true,
        urls: true,
        util: true,
        utils: true,
        val: true,
        vals: true,
      },
    },
  ],
  'unicorn/switch-case-braces': [
    'error',
    'avoid',
  ],
};
